# Generated by Django 5.0.7 on 2025-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemessage',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
