# Generated by Django 5.0.7 on 2025-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_alter_sitemessage_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemessage',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
