# Generated by Django 5.0.7 on 2025-08-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0003_sitemessage_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemessage',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
