# Generated by Django 5.0.7 on 2025-08-26 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0004_alter_sitemessage_telegram_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemessage',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Кому адресовано сообщение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitemessage',
            name='user',
            field=models.ForeignKey(help_text='Кто отправил сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
