# Generated by Django 5.0.7 on 2025-10-25 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0005_sitemessage_recipient_alter_sitemessage_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qwiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('answer_text', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll_id', models.IntegerField(blank=True, default=0, null=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Кому адресована викторина', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_qwiz', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Кто отправил викторину', on_delete=django.db.models.deletion.CASCADE, related_name='sent_qwiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
