# Generated by Django 5.0.7 on 2025-10-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0006_qwiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwiz',
            name='correct_answer',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='qwiz',
            name='answer_text',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
