# Generated by Django 5.0.7 on 2025-10-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0007_qwiz_correct_answer_alter_qwiz_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwiz',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
