# Generated by Django 5.0.7 on 2025-07-24 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_translate', models.CharField(max_length=30)),
                ('article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arcticle', to='words.article', verbose_name='Артикль')),
                ('lection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lection', to='words.lection', verbose_name='Лекция')),
                ('word_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='words.wordtype', verbose_name='Тип слова')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
