# Generated by Django 5.0.7 on 2025-07-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
