# Generated by Django 5.0.7 on 2025-07-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_word_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='words.word')),
                ('word_single', models.CharField(max_length=30)),
                ('word_plural', models.CharField(blank=True, max_length=30, null=True)),
                ('plural_sign', models.CharField(blank=True, max_length=5, null=True)),
                ('word_translate_plural', models.CharField(blank=True, max_length=30, null=True)),
            ],
            bases=('words.word',),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=30, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_translate',
            field=models.CharField(max_length=30, verbose_name='Перевод'),
        ),
    ]
