# Generated by Django 5.0.7 on 2025-07-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_noun_alter_word_word_alter_word_word_translate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noun',
            name='word_single',
        ),
    ]
