# Generated by Django 5.0.7 on 2025-07-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_remove_noun_word_single'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noun',
            options={'verbose_name': 'Существительное', 'verbose_name_plural': 'Существительные'},
        ),
        migrations.RemoveField(
            model_name='word',
            name='article',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_translate',
        ),
        migrations.AddField(
            model_name='noun',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arcticle', to='words.article', verbose_name='Артикль'),
        ),
        migrations.AddField(
            model_name='noun',
            name='word',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noun',
            name='word_translate',
            field=models.CharField(default=1, max_length=30, verbose_name='Перевод'),
            preserve_default=False,
        ),
    ]
