# Generated by Django 5.0.7 on 2025-07-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_alter_noun_options_remove_word_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='words.word')),
                ('word', models.CharField(max_length=30)),
                ('word_translate', models.CharField(max_length=30, verbose_name='Перевод')),
                ('ich_form', models.CharField(max_length=30)),
                ('du_form', models.CharField(max_length=30)),
                ('er_sie_es_form', models.CharField(max_length=30)),
                ('wir_form', models.CharField(max_length=30)),
                ('ihr_form', models.CharField(max_length=30)),
                ('Sie_sie', models.CharField(max_length=30)),
                ('past_prefect_form', models.CharField(blank=True, max_length=30, null=True)),
                ('past_pretorium_form', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Глагол',
                'verbose_name_plural': 'Глаголы',
            },
            bases=('words.word',),
        ),
    ]
