# Generated by Django 5.0.7 on 2025-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_verb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verb',
            old_name='Sie_sie',
            new_name='Sie_sie_form',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='past_pretorium_form',
            new_name='past_pretorium_Sie_sie_form',
        ),
        migrations.AddField(
            model_name='verb',
            name='past_pretorium_du_form',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='past_pretorium_er_sie_es_form',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='past_pretorium_ich_form',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='past_pretorium_ihr_form',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='past_pretorium_wir_form',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
