# Generated by Django 5.0.7 on 2025-07-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_rename_sie_sie_verb_sie_sie_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verb',
            old_name='past_pretorium_Sie_sie_form',
            new_name='past_perfect_form',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='past_prefect_form',
            new_name='past_prateritum_Sie_sie_form',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='past_pretorium_du_form',
            new_name='past_prateritum_du_form',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='past_pretorium_er_sie_es_form',
            new_name='past_prateritum_er_sie_es_form',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='past_pretorium_ich_form',
            new_name='past_prateritum_ich_form',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='past_pretorium_ihr_form',
            new_name='past_prateritum_ihr_form',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='past_pretorium_wir_form',
            new_name='past_prateritum_wir_form',
        ),
    ]
