# Generated by Django 5.0.7 on 2025-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_rename_past_pretorium_sie_sie_form_verb_past_perfect_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='past_prateritum_Sie_sie_form',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='past_prateritum_du_form',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='past_prateritum_er_sie_es_form',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='past_prateritum_ich_form',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='past_prateritum_ihr_form',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='past_prateritum_wir_form',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True),
        ),
    ]
