# Generated by Django 5.0.7 on 2025-08-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_alter_verb_past_prateritum_sie_sie_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='regal',
            field=models.BooleanField(default=True),
        ),
    ]
