# Generated by Django 5.0.7 on 2025-09-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_verb_regal'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='forms',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Формы'),
        ),
    ]
