# Generated by Django 5.0.7 on 2025-09-09 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0013_article_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='words.word')),
                ('word', models.CharField(max_length=30, verbose_name='Прилагательное')),
                ('translation', models.CharField(max_length=50, verbose_name='Перевод')),
                ('komparativ', models.CharField(blank=True, max_length=30, null=True, verbose_name='Сравнительная степень')),
                ('superlativ', models.CharField(blank=True, max_length=30, null=True, verbose_name='Превосходная степень')),
                ('declensions', models.JSONField(blank=True, default=dict, null=True, verbose_name='Склонение')),
            ],
            options={
                'verbose_name': 'Прилагательное',
                'verbose_name_plural': 'Прилагательные',
            },
            bases=('words.word',),
        ),
        migrations.AlterField(
            model_name='noun',
            name='word',
            field=models.CharField(max_length=30, verbose_name='Существительное'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='word',
            field=models.CharField(max_length=30, verbose_name='Глагол'),
        ),
    ]
