# Generated by Django 5.0.7 on 2025-09-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0014_adjective_alter_noun_word_alter_verb_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjective',
            old_name='translation',
            new_name='word_translate',
        ),
    ]
