# Generated by Django 5.0.7 on 2025-09-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0015_rename_translation_adjective_word_translate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numeral',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='words.word')),
                ('word', models.CharField(max_length=30, verbose_name='Числительное')),
                ('word_translate', models.CharField(max_length=50, verbose_name='Перевод')),
                ('oidinal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Прорядковый')),
                ('date_numeral', models.CharField(blank=True, max_length=30, null=True, verbose_name='Для даты')),
            ],
            options={
                'verbose_name': 'Числительное',
                'verbose_name_plural': 'Числительные',
            },
            bases=('words.word',),
        ),
    ]
