# Generated by Django 5.0.7 on 2025-09-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0016_numeral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numeral',
            old_name='oidinal',
            new_name='ordinal',
        ),
    ]
