# Generated by Django 5.0.7 on 2025-09-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0017_rename_oidinal_numeral_ordinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='words.word')),
                ('word', models.CharField(max_length=30, verbose_name='Местоимение')),
                ('word_translate', models.CharField(max_length=50, verbose_name='Перевод')),
                ('akkusativ', models.CharField(blank=True, max_length=30, null=True, verbose_name='Винительный падеж')),
                ('dativ', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дательный падеж')),
                ('prossessive', models.CharField(blank=True, max_length=30, null=True, verbose_name='Притяжательное')),
                ('reflexive', models.CharField(blank=True, max_length=30, null=True, verbose_name='Возвратное')),
            ],
            options={
                'verbose_name': 'Местоимение',
                'verbose_name_plural': 'Местоимения',
            },
            bases=('words.word',),
        ),
    ]
