# Generated by Django 5.0.7 on 2025-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0018_pronoun'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronoun',
            name='akkusativ_translate',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Перевод винительный падеж'),
        ),
        migrations.AddField(
            model_name='pronoun',
            name='dativ_translate',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Перевод дательный падеж'),
        ),
        migrations.AddField(
            model_name='pronoun',
            name='prossessive_translate',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Перевод притяжательное'),
        ),
        migrations.AddField(
            model_name='pronoun',
            name='reflexive_translate',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Перевод возвратное'),
        ),
    ]
