# Generated by Django 5.0.7 on 2025-09-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0019_pronoun_akkusativ_translate_pronoun_dativ_translate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lections', to='words.book', verbose_name='книга'),
        ),
        migrations.CreateModel(
            name='NounDeclensionsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativ', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('genitiv', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('dativ', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('akkusativ', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('plural_nominativ', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('plural_genitiv', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('plural_dativ', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('plural_akkusativ', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('noun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declension_forms', to='words.noun')),
            ],
            options={
                'verbose_name': 'Склонение существительного',
                'verbose_name_plural': 'Склонения существительного',
            },
        ),
    ]
