# Generated by Django 5.0.7 on 2025-10-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0020_alter_lection_book_noundeclensionsform'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherWords',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='words.word')),
                ('word', models.CharField(max_length=30, verbose_name='Слово')),
                ('word_translate', models.CharField(max_length=30, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Остальное слово',
                'verbose_name_plural': 'Остальные слова',
            },
            bases=('words.word',),
        ),
    ]
