# Generated by Django 5.0.7 on 2025-07-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='scores',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
