# Generated by Django 5.0.7 on 2025-07-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='lifes',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
