# Generated by Django 5.0.7 on 2025-07-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_lifes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='scores',
            new_name='score',
        ),
    ]
