# Generated by Django 5.0.7 on 2025-08-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0004_rename_scores_baseuser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='common.userrole'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
