# Generated by Django 5.0.7 on 2025-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_baseuser_user_role_alter_baseuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='last_life_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
