# Generated by Django 5.0.7 on 2025-08-13 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_baseuser_last_life_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='last_life_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
