# Generated by Django 5.0.7 on 2025-08-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_baseuser_last_life_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='user_bot_id',
            new_name='chat_id',
        ),
    ]
