# Generated by Django 5.0.7 on 2025-08-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_bot_id_baseuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='telegram_username',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
