# Generated by Django 5.0.7 on 2025-11-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_baseuser_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='user_bot_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
